name: 'EUserv Auto Extend'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '50 0 * * *'

jobs:
  auto_renew:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@master

      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade requests
          python -m pip install --upgrade beautifulsoup4
      - name: log push  #获得自动部署的时间
        run: | 
          echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
      - name: Commit #上传到仓库
        run: |
          git config --global user.email AutoupdateRobot@email.com
          git config --global user.name AutoupdateRobot
          git fetch --all
          git pull --all
          git add .
          git commit -m "update new push" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: 'Auto_renew'
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python main.py
      
